use super::types::BuiltinKnowledgeDoc;

macro_rules! doc {
    ($id:literal, $path:literal, $content:expr) => {
        BuiltinKnowledgeDoc {
            id: $id,
            virtual_path: $path,
            content: $content,
        }
    };
}

pub static BUILTIN_DOCS: &[BuiltinKnowledgeDoc] = &[
    doc!(
        "nenjo.domain.nenjo",
        "builtin://nenjo/domain/nenjo.md",
        include_str!("../../docs/domain/nenjo.md")
    ),
    doc!(
        "nenjo.domain.platform",
        "builtin://nenjo/domain/platform.md",
        include_str!("../../docs/domain/platform.md")
    ),
    doc!(
        "nenjo.domain.sdk",
        "builtin://nenjo/domain/sdk.md",
        include_str!("../../docs/domain/sdk.md")
    ),
    doc!(
        "nenjo.guide.abilities",
        "builtin://nenjo/guide/abilities.md",
        include_str!("../../docs/guide/abilities.md")
    ),
    doc!(
        "nenjo.guide.agents",
        "builtin://nenjo/guide/agents.md",
        include_str!("../../docs/guide/agents.md")
    ),
    doc!(
        "nenjo.guide.context_blocks",
        "builtin://nenjo/guide/context-blocks.md",
        include_str!("../../docs/guide/context-blocks.md")
    ),
    doc!(
        "nenjo.guide.prompt_structuring",
        "builtin://nenjo/guide/prompt-structuring.md",
        include_str!("../../docs/guide/prompt-structuring.md")
    ),
    doc!(
        "nenjo.guide.knowledge_packs",
        "builtin://nenjo/guide/knowledge-packs.md",
        include_str!("../../docs/guide/knowledge-packs.md")
    ),
    doc!(
        "nenjo.guide.councils",
        "builtin://nenjo/guide/councils.md",
        include_str!("../../docs/guide/councils.md")
    ),
    doc!(
        "nenjo.guide.domains",
        "builtin://nenjo/guide/domains.md",
        include_str!("../../docs/guide/domains.md")
    ),
    doc!(
        "nenjo.guide.executions",
        "builtin://nenjo/guide/executions.md",
        include_str!("../../docs/guide/executions.md")
    ),
    doc!(
        "nenjo.guide.memory",
        "builtin://nenjo/guide/memory.md",
        include_str!("../../docs/guide/memory.md")
    ),
    doc!(
        "nenjo.guide.projects",
        "builtin://nenjo/guide/projects.md",
        include_str!("../../docs/guide/projects.md")
    ),
    doc!(
        "nenjo.guide.routines",
        "builtin://nenjo/guide/routines.md",
        include_str!("../../docs/guide/routines.md")
    ),
    doc!(
        "nenjo.guide.scopes",
        "builtin://nenjo/guide/scopes.md",
        include_str!("../../docs/guide/scopes.md")
    ),
    doc!(
        "nenjo.guide.tasks",
        "builtin://nenjo/guide/tasks.md",
        include_str!("../../docs/guide/tasks.md")
    ),
    doc!(
        "nenjo.reference.knowledge.domain_documents",
        "builtin://nenjo/reference/knowledge/domain-documents.md",
        include_str!("../../docs/reference/knowledge/domain_documents.md")
    ),
    doc!(
        "nenjo.reference.knowledge.entity_documents",
        "builtin://nenjo/reference/knowledge/entity-documents.md",
        include_str!("../../docs/reference/knowledge/entity_documents.md")
    ),
    doc!(
        "nenjo.reference.knowledge.guide_documents",
        "builtin://nenjo/reference/knowledge/guide-documents.md",
        include_str!("../../docs/reference/knowledge/guide_documents.md")
    ),
    doc!(
        "nenjo.reference.knowledge.policy_documents",
        "builtin://nenjo/reference/knowledge/policy-documents.md",
        include_str!("../../docs/reference/knowledge/policy_documents.md")
    ),
    doc!(
        "nenjo.reference.knowledge.reference_documents",
        "builtin://nenjo/reference/knowledge/reference-documents.md",
        include_str!("../../docs/reference/knowledge/reference_documents.md")
    ),
    doc!(
        "nenjo.reference.knowledge.taxonomy_documents",
        "builtin://nenjo/reference/knowledge/taxonomy-documents.md",
        include_str!("../../docs/reference/knowledge/taxonomy_documents.md")
    ),
    doc!(
        "nenjo.reference.resource_dependency_order",
        "builtin://nenjo/reference/resource-dependency-order.md",
        include_str!("../../docs/reference/resource-dependency-order.md")
    ),
    doc!(
        "nenjo.reference.template_vars",
        "builtin://nenjo/reference/template-vars.md",
        include_str!("../../docs/reference/template-vars.md")
    ),
    doc!(
        "nenjo.taxonomy.tasks",
        "builtin://nenjo/taxonomy/tasks.md",
        include_str!("../../docs/taxonomy/tasks.md")
    ),
    doc!(
        "nenjo.taxonomy.resource_surfaces",
        "builtin://nenjo/taxonomy/resource-surfaces.md",
        include_str!("../../docs/taxonomy/resource_surfaces.md")
    ),
    doc!(
        "nenjo.taxonomy.workflow_patterns",
        "builtin://nenjo/taxonomy/workflow-patterns.md",
        include_str!("../../docs/taxonomy/workflow_patterns.md")
    ),
];
