[workspace]
repo_url = "https://github.com/nenjo-ai/nenjo"
git_tag_enable = false
git_release_enable = false
changelog_update = false

[[package]]
name = "nenjo"
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_enable = true
git_release_name = "v{{ version }}"
changelog_update = true
changelog_path = "CHANGELOG.md"
changelog_include = [
    "nenjo-cli",
    "nenjo-crypto-auth",
    "nenjo-eventbus",
    "nenjo-xml",
    "nenjo-models",
    "nenjo-events",
    "nenjo-harness",
    "nenjo-integration-tests",
    "nenjo-knowledge",
    "nenjo-platform",
    "nenjo-secure-envelope",
    "nenjo-sessions",
    "nenjo-tool-api",
    "nenjo-worker",
]

[[package]]
name = "nenjo-cli"

[[package]]
name = "nenjo-crypto-auth"

[[package]]
name = "nenjo-eventbus"

[[package]]
name = "nenjo-events"

[[package]]
name = "nenjo-harness"

[[package]]
name = "nenjo-integration-tests"

[[package]]
name = "nenjo-knowledge"

[[package]]
name = "nenjo-models"

[[package]]
name = "nenjo-platform"

[[package]]
name = "nenjo-secure-envelope"

[[package]]
name = "nenjo-sessions"

[[package]]
name = "nenjo-tool-api"

[[package]]
name = "nenjo-worker"

[[package]]
name = "nenjo-xml"
